### ISSUE TITLE
REQUEST: Import values from existing PDF

### ISSUE THREAD

**Issue by Zamrod** [farling42/fvtt-pdf-pager#24]
Since the module can already take values from Foundry and put them into a PDF to use as a character sheet it would be nice to be able to do the reverse and take values from a form fillable PDF and put them into Foundry. I run a lot of online games for strangers that have their characters already filled out in the default dnd5e character sheet and it would be nice to get at least most of the values imported from that.

**Comment by farling42** [comment]
That is already possible. Each PDF is different, so you have to set up the mapping yourself between the PDF field and the Actor field. Instructions are in the Readme file and the github main page. Regards,MartinOn 12 Oct 2022 02:03, Zamrod ***@***.***> wrote:
Since the module can already take values from Foundry and put them into a PDF to use as a character sheet it would be nice to be able to do the reverse and take values from a form fillable PDF and put them into Foundry. I run a lot of online games for strangers that have their characters already filled out in the default dnd5e character sheet and it would be nice to get at least most of the values imported from that.

**Comment by farling42** [comment]
See https://github.com/farling42/fvtt-pdf-pager#format-of-the-mapping-object

You can prepare the file in a text editor, and then paste the contents of the file into the relevant text box in the module configuration settings.

**Comment by farling42** [comment]
This facility is available in 0.20.0.
It is controlled by a check box in the module settings.
When selected, the data within a PDF file will be loaded into the mapped Actor fields when the PDF window is opened.
Editing within the PDF window is disabled when the option is enabled, in order to prevent the user from making local changes to the Actor which will be overwritten when the PDF window is next opened.
